name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          submodules: true

      - name: Run Test
        run: cargo test
